# Copy from https://github.com/spf13/cobra
# https://github.com/spf13/cobra/blob/master/LICENSE.txt
name: Test
on:
  push:
  pull_request:
env:
  GO111MODULE: on
jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        go-version: [ 1.16.x,1.17.x,1.18beta1 ]
    name: '${{ matrix.os }} | ${{ matrix.go-version }}'
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          stable: ${{ !contains(matrix.go, 'beta') }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-${{ matrix.go }}-

      - run: |
          export GOBIN=$HOME/go/bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b $GOBIN latest
          go get -u github.com/kyoh86/richgo
          go get -u github.com/mitchellh/gox
      - run: PATH=$HOME/go/bin/:$PATH make